name: Notify Portal
on:
  release:
    types: [published]

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch signal to Portal
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.ORG_ADMIN_TOKEN }}
          repository: ${{ github.repository_owner }}/${{ vars.PORTAL_REPO_NAME }}
          event-type: app-update
          client-payload: '{"app_name": "${{ github.event.repository.name }}", "version": "${{ github.event.release.tag_name }}"}'